echo to victory

diff --git a/.github/actions/versioning/action.yml b/.github/actions/versioning/action.yml
--- a/.github/actions/versioning/action.yml
+++ b/.github/actions/versioning/action.yml
@@ -32,59 +32,64 @@ runs:
 
         # Check if there are changes in the package folder
         CHANGED_FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA './${{ github.event.repository.name }}/')
+        echo "Changed files: $CHANGED_FILES"
+
+    - name: Quit if no changes
+      shell: bash
+      run: |
+        if [[ -z "$CHANGED_FILES" ]]; then
+          echo "There are no changes in the ${{ github.event.repository.name }} folder"
+          exit 0
+        fi
 
     - name: Execute setup.py versioning checks
       if: inputs.packaging-style == 'setup.py'
       shell: bash
       run: |
-        if [[ -n "$CHANGED_FILES" ]]; then
-          echo "------------------------------------------"
-          echo "There are changes in the ${{ github.event.repository.name }} folder"
-          echo "------------------------------------------"
-          echo "Checking __init__.py file..."
+        echo "------------------------------------------"
+        echo "There are changes in the ${{ github.event.repository.name }} folder"
+        echo "------------------------------------------"
+        echo "Checking __init__.py file..."
 
-          head_init_version=$(git show HEAD:./${{ github.event.repository.name }}/__init__.py | grep -oP '__version__ = "\K[^"]+')
-          echo "Head version: ${head_init_version}"
+        head_init_version=$(git show HEAD:./${{ github.event.repository.name }}/__init__.py | grep -oP '__version__ = "\K[^"]+')
+        echo "Head version: ${head_init_version}"
 
-          base_init_version=$(git show ${BASE_SHA}:./${{ github.event.repository.name }}/__init__.py | grep -oP '__version__ = "\K[^"]+')
-          echo "Base version: ${base_init_version}"
+        base_init_version=$(git show ${BASE_SHA}:./${{ github.event.repository.name }}/__init__.py | grep -oP '__version__ = "\K[^"]+')
+        echo "Base version: ${base_init_version}"
 
-          if [ "$base_init_version" != "$head_init_version" ]; then
-            echo "The __version__ variable has been updated in package init."
-          else
-            echo "Error: The __version__ variable has not been updated in package init."
-            exit 1
-          fi
-
-          echo "------------------------------------------"
-          echo "Checking setup.py file..."
-
-          head_setup_version=$(git show HEAD:./setup.py | grep -oP 'version="\K[^"]+')
-          echo "Head version: ${head_setup_version}"
-
-          base_setup_version=$(git show ${BASE_SHA}:./setup.py | grep -oP 'version="\K[^"]+')
-          echo "Base version: ${base_setup_version}"
-
-          if [ "$head_setup_version" != "$base_setup_version" ]; then
-            echo "The version variable have both been updated in setup.py."
-          else
-            echo "Error: The version variable has not been updated in setup.py."
-            exit 1
-          fi
-
-          echo "------------------------------------------"
-          echo "Checking they are equal..."
-
-          if [ "$head_init_version" == "$head_setup_version" ]; then
-            echo "The versions are equal."
-          else
-            echo "Error: The versions are not equal."
-            exit 1
-          fi
+        if [ "$base_init_version" != "$head_init_version" ]; then
+          echo "The __version__ variable has been updated in package init."
         else
-          echo "There are no changes in the ${{ github.event.repository.name }} folder"
-          exit 0
+          echo "Error: The __version__ variable has not been updated in package init."
+          exit 1
         fi
+
+        echo "------------------------------------------"
+        echo "Checking setup.py file..."
+
+        head_setup_version=$(git show HEAD:./setup.py | grep -oP 'version="\K[^"]+')
+        echo "Head version: ${head_setup_version}"
+
+        base_setup_version=$(git show ${BASE_SHA}:./setup.py | grep -oP 'version="\K[^"]+')
+        echo "Base version: ${base_setup_version}"
+
+        if [ "$head_setup_version" != "$base_setup_version" ]; then
+          echo "The version variable have both been updated in setup.py."
+        else
+          echo "Error: The version variable has not been updated in setup.py."
+          exit 1
+        fi
+
+        echo "------------------------------------------"
+        echo "Checking they are equal..."
+
+        if [ "$head_init_version" == "$head_setup_version" ]; then
+          echo "The versions are equal."
+        else
+          echo "Error: The versions are not equal."
+          exit 1
+        fi
+
 
     - name: Execute pyproject.toml versioning checks
       shell: bash
